name: A workflow for my Hello One Piece file
on: push

jobs:
  build:
    name: Hello One Piece action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Luffy"
