name: A workflow for my Hello One Piece file
on: push

jobs:
  build:
    name: Hello One Piece action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Luffy"
      - name: set output parameter
        id: vars
        run: echo ::set-output name=WHAT_I_WANT::"To be the king of pirates"
